apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logbook.fullname" . }}
  labels:
    {{- include "logbook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "logbook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "logbook.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "logbook.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.logbook.namespace }}
            - name: LOGBOOK_TARGET_NAMESPACE
              value: {{ .Values.logbook.namespace | quote }}
            {{- end }}
            {{- if .Values.logbook.log.format }}
            - name: LOGBOOK_LOG_FORMAT
              value: {{ .Values.logbook.log.format | quote }}
            {{- end }}
            {{- if .Values.logbook.log.out }}
            - name: LOGBOOK_LOG_OUT
              value: {{ .Values.logbook.log.out | quote }}
            {{- end }}
            {{- if .Values.logbook.log.level }}
            - name: LOGBOOK_LOG_LEVEL
              value: {{ .Values.logbook.log.level | quote }}
            {{- end }}
            {{- if .Values.logbook.log.filename }}
            - name: LOGBOOK_LOG_FILENAME
              value: {{ .Values.logbook.log.filename | quote }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
