name: Build

on: 
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

permissions:
  id-token: write
  contents: read
  security-events: write
  packages: write

env:
  REGISTRY_URL: ghcr.io
  VERSION: 0.1.0
  USERNAME: sundi0331

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set IMAGE_TAG for main branch
        if: github.ref_name == 'main'
        run: |
          echo "IMAGE_TAG=${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Set IMAGE_TAG for other branches
        if: github.ref_name != 'main'
        run: |
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker build
        run: |
          docker buildx build -f Dockerfile \
            -t ${{ env.REGISTRY_URL }}/${{ github.repository }}:${{ env.IMAGE_TAG }} \
            --label "org.opencontainers.image.created=$(date -u --iso-8601=seconds)" \
            --label "org.opencontainers.image.authors=${{ env.USERNAME }}" \
            --label "org.opencontainers.image.url=${{ github.repositoryUrl }}" \
            --label "org.opencontainers.image.documentation=${{ github.repositoryUrl }}" \
            --label "org.opencontainers.image.source=${{ github.repositoryUrl }}" \
            --label "org.opencontainers.image.version=${{ env.IMAGE_TAG }}" \
            --label "org.opencontainers.image.revision=${{ github.sha }}" \
            --label "org.opencontainers.image.title=${{ github.event.repository.name }}" \
            --label "org.opencontainers.image.description=Logbook is a kubernetes event logger which can be used either in-cluster(use kubernetes ServiceAccount for auth) or out-of-cluster(use kubeconfig file for auth)." \
            .

      - name: Docker push
        run: docker push ${{ env.REGISTRY_URL }}/${{ github.repository }}:${{ env.IMAGE_TAG }}

      - name: Install cosign
        uses: sigstore/cosign-installer@main

      - name: Sign the images with GitHub OIDC Token
        env:
          COSIGN_EXPERIMENTAL: true
        run: cosign sign -y ${{ env.REGISTRY_URL }}/${{ github.repository }}:${{ env.IMAGE_TAG }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REGISTRY_URL }}/${{ github.repository }}:${{ env.IMAGE_TAG }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
