name: Release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
      
      - name: Build Linux amd64
        run: |
          GOOS=linux GOARCH=amd64 go build -o logbook_${{ github.event.inputs.version }}_linux_x86_64

      - name: Build Linux amd64
        run: |
          GOOS=windows GOARCH=amd64 go build -o logbook_${{ github.event.inputs.version }}_windows_x86_64.exe
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: |
            logbook_${{ github.event.inputs.version }}_linux_x86_64
            logbook_${{ github.event.inputs.version }}_windows_x86_64.exe
